---
version: 3

images:
  base_image:
    name: 'quay.io/centos/centos:stream9'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base:
    - RUN dnf -y update && 
        dnf -y install 
          openssh-clients 
          sshpass 
          rsync 
          python3-devel 
          gcc 
          openssl-devel 
          libffi-devel 
          krb5-devel 
          krb5-libs 
          krb5-workstation 
          libxml2-devel 
          libxslt-devel 
          cyrus-sasl-devel 
          cyrus-sasl-gssapi && 
        dnf clean all

  prepend_galaxy:
    - COPY _build/requirements.yml /tmp/requirements.yml

  append_final:
    - RUN chmod -R g+rw /opt/ansible
    - USER ansible
