---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base:
    - RUN dnf -y update && dnf clean all
  prepend_galaxy:
    - RUN pip3 install --upgrade pip setuptools wheel
  append_final:
    - RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - RUN echo -e "[azure-cli]\nname=Azure CLI\nbaseurl=https://packages.microsoft.com/yumrepos/azure-cli\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/azure-cli.repo
    - RUN dnf install -y azure-cli
