---
collections:
  - name: azure.azcollection
    version: ">=1.19.0"
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com
  - name: community.general
    version: ">=7.0.0"
    source: https://galaxy.ansible.com
  - name: community.crypto
    version: ">=2.15.0"
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: ">=2.4.0"
    source: https://galaxy.ansible.com
  - name: ansible.windows
    version: ">=1.14.0"
    source: https://galaxy.ansible.com
  - name: community.windows
    version: ">=1.13.0"
    source: https://galaxy.ansible.com
