all:
  children:
    azure:
      hosts:
        localhost:
          ansible_connection: local
      vars:
        azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
        azure_tenant: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
        azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        azure_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
    
    windows:
      hosts:
        win-server-01:
          ansible_host: 192.168.1.100
          ansible_user: "{{ lookup('env', 'WINDOWS_USERNAME') }}"
          ansible_password: "{{ lookup('env', 'WINDOWS_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: credssp
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
        
        win-server-02:
          ansible_host: 192.168.1.101
          ansible_user: "{{ lookup('env', 'WINDOWS_USERNAME') }}"
          ansible_password: "{{ lookup('env', 'WINDOWS_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
