all:
  children:
    redhat_servers:
      hosts:
        rhel-server-01:
          ansible_host: 192.168.1.10
          ansible_user: "{{ lookup('env', 'RHEL_USERNAME') | default('ansible') }}"
          ansible_password: "{{ lookup('env', 'RHEL_PASSWORD') }}"
          ansible_connection: ssh
          ansible_become: true
          ansible_become_method: sudo
        
        rhel-server-02:
          ansible_host: 192.168.1.11
          ansible_user: "{{ lookup('env', 'RHEL_USERNAME') | default('ansible') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_FILE') | default('~/.ssh/id_rsa') }}"
          ansible_connection: ssh
          ansible_become: true
          ansible_become_method: sudo
          
        centos-server-01:
          ansible_host: 192.168.1.12
          ansible_user: "{{ lookup('env', 'CENTOS_USERNAME') | default('centos') }}"
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_FILE') | default('~/.ssh/id_rsa') }}"
          ansible_connection: ssh
          ansible_become: true
          ansible_become_method: sudo
      
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    windows_servers:
      hosts:
        win-server-01:
          ansible_host: 192.168.1.100
          ansible_user: "{{ lookup('env', 'WINDOWS_USERNAME') }}"
          ansible_password: "{{ lookup('env', 'WINDOWS_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: credssp
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
        
        win-server-02:
          ansible_host: 192.168.1.101
          ansible_user: "{{ lookup('env', 'WINDOWS_USERNAME') }}"
          ansible_password: "{{ lookup('env', 'WINDOWS_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
          
        win-domain-server:
          ansible_host: 192.168.1.102
          ansible_user: "{{ lookup('env', 'DOMAIN_USERNAME') }}"
          ansible_password: "{{ lookup('env', 'DOMAIN_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: kerberos
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
