all:
  children:
    redhat_servers:
      hosts:    
    windows_servers:
      hosts:
        winlab.brainstormes.org:
          ansible_host: 192.168.6.5
          ansible_user: "{{ lookup('env', 'WINDOWS_USERNAME') }}"
          ansible_password: "{{ lookup('env', 'WINDOWS_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: credssp
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
        
        winlab3.brainstormes.org:
          ansible_host: 192.168.6.80
          ansible_user: "{{ lookup('env', 'WINDOWS_USERNAME') }}"
          ansible_password: "{{ lookup('env', 'WINDOWS_PASSWORD') }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5986
